const countryNames = {
  Algeria: 'AL',
  Angola: 'AN',
  Bantu: 'BA',
  Benin: 'BE',
  Botswana: 'BT',
  'Burkina Faso': 'BF',
  Burundi: 'BR',
  Bushman: 'BU',
  Bushongo: 'BH',
  Cameroon: 'CR',
  'Canary Is.': 'CI',
  'Cape Verde': 'CV',
  'Central African Republic': 'CA',
  Dahomean: 'DH',
  'Democratic Republic of the Congo': 'DC',
  Egypt: 'EG',
  Eritrea: 'ER',
  Ethiopia: 'ET',
  Gabon: 'GB',
  Gambia: 'GA',
  Ghana: 'GH',
  'Gold Coast': 'GC',
  Guinea: 'GU',
  Hottentot: 'HO',
  'Ivory Coast': 'IC',
  Kenya: 'KY',
  Lesotho: 'LE',
  Liberia: 'LI',
  Libya: 'LB',
  Madagascar: 'MD',
  Malawi: 'MW',
  Mali: 'ML',
  Mande: 'MN',
  Mauritania: 'MU',
  Mauritius: 'MA',
  Mbundu: 'MB',
  Mende: 'ME',
  Morocco: 'MR',
  Mozambique: 'MZ',
  Namibia: 'NM',
  Niger: 'NG',
  Nigeria: 'NI',
  Pygmy: 'PY',
  'Republic of Chad': 'CH',
  'Republic of Djibouti': 'RD',
  'Republic of Equatorial Guinea': 'RE',
  'Republic of Guinea- Bissau': 'RG',
  'Republic of Sao Tome and Principe': 'RS',
  'Republic of Seychelles': 'SY',
  'Republic of the Congo(Congo - Brazzaville)': 'RC',
  'Reunion Island': 'RI',
  Rwanda: 'RW',
  Semitic: 'SE',
  Senegal: 'SN',
  'Sierra Leone': 'SL',
  Somalia: 'SO',
  'South Africa': 'SA',
  ' South Sudan': 'SS',
  Sudan: 'SU',
  Swahili: 'SH',
  Swaziland: ' SW',
  Tanzania: 'TA',
  Togo: 'TO',
  Tunisia: 'TN',
  Uganda: 'UG',
  'Union of the Comoros': 'UC',
  Yao: 'YA',
  Zaire: 'ZA',
  Zambia: 'ZM',
  Zimbabwe: 'ZI',
  Zulu: 'ZU',
};

export default countryNames;
